// @flow

export default {
  LOCAL_STATE_GET_DEFAULT_SHOPPING_LIST: 'LOCAL_STATE_GET_DEFAULT_SHOPPING_LIST',
  LOCAL_STATE_SET_DEFAULT_SHOPPING_LIST: 'LOCAL_STATE_SET_DEFAULT_SHOPPING_LIST',
  LOCAL_STATE_DEFAULT_SHOPPING_LIST_CHANGED: 'LOCAL_STATE_DEFAULT_SHOPPING_LIST_CHANGED',
};
