// @flow

export default {
  PRODUCTS_FILTER_SORT_OPTION_CHANGED: 'PRODUCTS_FILTER_SORT_OPTION_CHANGED',
  PRODUCTS_FILTER_CATEGORIES_CHANGED: 'PRODUCTS_FILTER_CATEGORIES_CHANGED',
  PRODUCTS_FILTER_STORES_CHANGED: 'PRODUCTS_FILTER_STORES_CHANGED',
};
