// @flow

export default {
  SPECIALS_FILTER_SORT_OPTION_CHANGED: 'SPECIALS_FILTER_SORT_OPTION_CHANGED',
  SPECIALS_FILTER_CATEGORIES_CHANGED: 'SPECIALS_FILTER_CATEGORIES_CHANGED',
  SPECIALS_FILTER_STORES_CHANGED: 'SPECIALS_FILTER_STORES_CHANGED',
};
