// @flow

export default {
  PRODUCTS_SEARCH_KEYWORD_CHANGED: 'PRODUCTS_SEARCH_KEYWORD_CHANGED',
  PRODUCTS_FILTER_OPTION_CHANGED: 'PRODUCTS_FILTER_OPTION_CHANGED',
  PRODUCTS_PRODUCT_SELECTED: 'PRODUCTS_PRODUCT_SELECTED',
  PRODUCTS_PRODUCT_DESELECTED: 'PRODUCTS_PRODUCT_DESELECTED',
  PRODUCTS_SEARCHING_MODE_CHANGED: 'PRODUCTS_SEARCHING_MODE_CHANGED',
};
