// @flow

export default {
  APP_UPDATER_NOT_STARTED: 'APP_UPDATER_NOT_STARTED',
  APP_UPDATER_CHECKING_FOR_UPDATE: 'APP_UPDATER_CHECKING_FOR_UPDATE',
  APP_UPDATER_DOWNLOADING_UPDATE: 'APP_UPDATER_DOWNLOADING_UPDATE',
  APP_UPDATER_INSTALLING_UPDATE: 'APP_UPDATER_INSTALLING_UPDATE',
  APP_UPDATER_SUCCEEDED: 'APP_UPDATER_SUCCEEDED',
  APP_UPDATER_FAILED: 'APP_UPDATER_FAILED',
  APP_UPDATER_CLEAR_ERROR: 'APP_UPDATER_CLEAR_ERROR',
};
