// @flow

export default {
  SHOPPING_LIST_CURRENT_VIEWING_STAPLE_ITEM_CHANGED: 'SHOPPING_LIST_CURRENT_VIEWING_STAPLE_ITEM_CHANGED',
  SHOPPING_LIST_REMOVE_CURRENT_VIEWING_STAPLE_ITEM_FLAG_CHANGED: 'SHOPPING_LIST_REMOVE_CURRENT_VIEWING_STAPLE_ITEM_FLAG_CHANGED',
};
