// @flow

export default {
  STAPLE_ITEMS_SEARCH_KEYWORD_CHANGED: 'STAPLE_ITEMS_SEARCH_KEYWORD_CHANGED',
  STAPLE_ITEMS_ITEMS_ADDED: 'STAPLE_ITEMS_ITEMS_ADDED',
  STAPLE_ITEMS_ITEM_SELECTION_CHANGED: 'STAPLE_ITEMS_ITEM_SELECTION_CHANGED',
};
