// @flow

export default {
  STAPLE_SHOPPING_LIST_SEARCH_KEYWORD_CHANGED: 'STAPLE_SHOPPING_LIST_SEARCH_KEYWORD_CHANGED',
  STAPLE_SHOPPING_LIST_ITEMS_ADDED: 'STAPLE_SHOPPING_LIST_ITEMS_ADDED',
  STAPLE_SHOPPING_LIST_ITEM_SELECTION_CHANGED: 'STAPLE_SHOPPING_LIST_ITEM_SELECTION_CHANGED',
  STAPLE_SHOPPING_LIST_USER_ID_CHANGED: 'STAPLE_SHOPPING_LIST_USER_ID_CHANGED',
  STAPLE_SHOPPING_LIST_SHOPPING_LIST_CHANGED: 'STAPLE_SHOPPING_LIST_SHOPPING_LIST_CHANGED',
};
